# Generated by Django 6.0 on 2026-03-31 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_cart_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
            preserve_default=False,
        ),
    ]
